config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :index, :edit, :update]
  post 'follow/:id' => 'relationships#create', as: 'follow'
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow'
  get 'users/:id/following' => 'relationships#follower', as: 'following'
  get 'users/:id/followers' => 'relationships#followed', as: 'followers'
  get 'search' => 'searches#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def self.search(search, word)
    if search == "forward_match"
                        @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
                        @book = Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
                        @book = Book.where("#{word}")
    elsif search == "partial_match"
                        @book = Book.where("title LIKE?","%#{word}%")
    else
                        @book = Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name,    uniqueness: true, length: { in: 2..20 }
  validates :introduction,    length: { maximum: 50 }
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :favorited_books, through: :favorites, source: :book
  def follow(user_id)
    follower.create(followed_id: user_id)
  end


  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end


  def following?(user)
    following_user.include?(user)
  end

  def self.search(search,word)
    if search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
      @user = User.where("#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book_image = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book_image.id
    comment.save
    redirect_to book_path(book_image)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book was created successfully"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all.sort {|a,b| b.favorited_users.count <=> a.favorited_users.count}
    @user = current_user
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @user = User.find(@books.user.id)
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id == current_user.id
    else
      redirect_to books_path
    end
  end

  def update
     @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was updated successfully"
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    current_user.unfollow(params[:id])
    redirect_back(fallback_location: root_path)
  end

  def follower
    @user = User.find(params[:id])
  end

  def followed
    @user = User.find(params[:id])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    search = params[:search]
    @word = params[:word]
    if @range == '1'
      @user = User.search(search,@word)
    else
      @book = Book.search(search,@word)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: params[:id])
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User info was successfully updated"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/Destroy.js.erb
$(".comments").html("<%= escape_javascript(render partial: 'book_comments/comment', locals: {books: @books,book_comment: @book_comment) %>");

app/views/book_comments/_comment.html.erb
      <table class="comments">
          <tbody>
            <% books.book_comments.each do |book_comment| %>
            <tr>
              <td>
                <%= link_to user_path(book_comment.user_id) do %>
                <%= attachment_image_tag book_comment.user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
                <br>
                <%= book_comment.user.name %>
                <% end %>
              </td>
              <td>
                <%= book_comment.comment %>
              </td>
              <td>
                <% if book_comment.user == current_user %>
                <div class="comment-delete">
                  <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn-sm btn-danger" %>
                </div>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
      </table>
      <div>
      <%= form_with(model:[books, book_comment], remote: true) do |f| %>
        <%= f.text_area :comment, class: "form-control" %>
        <br>
        <%= f.submit "送信" %>
      <% end %>
      </div>

app/views/book_comments/create.js.erb
$(".comments").html("<%= escape_javascript(render partial: 'book_comments/comment', locals: {books: @books,book_comment: @book_comment) %>");

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <%= @book.errors.count %>error prohibited this obj from being saved:
          <% @book.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
      <%= form_with model:@book, local:true do |f| %>
      <div class="form-group">
        <label>Title</label>
        <%= f.text_field :title, class:"form-control book_title" %>
      </div>
      <div class="form-group">
        <label>Opinion</label>
        <%= f.text_area :body, class:"form-control book_body" %>
      </div>
      <div class="form-group"><%= f.submit "Update Book", class:"btn btn-success" %></div>
      <% end %>
      <%= link_to "Show", book_path(params[:id]) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
    <%= render 'users/userinfo', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </tread>
        <tbody>
          <% @books.each do |books| %>
          <tr>
            <td>
              <%= link_to user_path(books.user_id) do %>
              <%= attachment_image_tag books.user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td><%= link_to books.title, book_path(books.id) %></td>
            <td><%= books.body %></td>
            <td class="favorite_<%= books.id %>">
              <%= render 'favorites/favorite', books: books %>
            </td>
            <td>
              <%= link_to "コメント数：#{books.book_comments.count}", book_path(books.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
    <%= render 'users/userinfo', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <% if current_user.id == @user.id %>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
              <%= attachment_image_tag @user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
              <br>
              <%= @user.name %>
              <% end %>
            </td>
            <td><%= link_to @books.title, book_path(@books.id) %></td>
            <td><%= @books.body %></td>
            <td class="favorite">
              <%= render 'favorites/favorite', books: @books %>
            </td>
            <td>
              <%= link_to "コメント数：#{@books.book_comments.count}", book_path(@books.id) %>
            </td>
            <td>
              <%= link_to "Edit", edit_book_path(params[:id]), class: "btn-sm btn-success" %>
            </td>
            <td>
              <%= link_to "Destroy", book_path(params[:id]), method: :delete, class: "btn-sm btn-danger", "data-confirm" => "本当に消しますか？" %>
            </td>
          </tr>
          <% else %>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
              <%= attachment_image_tag @user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
              <br>
              <%= @user.name %>
              <% end %>
            </td>
            <td><%= link_to @books.title, book_path(@books.id) %></td>
            <td><%= @books.body %></td>
            <td class="favorite">
              <%= render 'favorites/favorite', books: @books %>
            </td>
            <td>
              <%= link_to "コメント数：#{@books.book_comments.count}", book_path(@books.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="comments">
        <%= render 'book_comments/comment', books: @books,book_comment: @book_comment %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/_favorite.html.erb
              <% if books.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorites_path(books), method: :delete, remote: true do %>
                    <font color="red">♥<%= books.favorites.count %></font>
                  <% end %>
                </p>
                <% else %>
                <p>
                  <%= link_to book_favorites_path(books), method: :post, remote: true do %>
                    ♥<%= books.favorites.count %>
                  <% end %>
                </p>
              <% end %>

app/views/favorites/create.js.erb
$(".favorite_<%= @book.id %>").html("<%= escape_javascript(render partial: 'favorites/favorite', locals: {books: @book}) %>");

app/views/favorites/destroy.js.erb
$(".favorite_<%= @book.id %>").html("<%= escape_javascript(render partial: 'favorites/favorite', locals: {books: @book}) %>");

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/followed.html.erb
<h1>Follower Users</h1>
<% if @user.follower_user.present? %>
  <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
          <% @user.follower_user.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user , :profile_image, size: "40x40", fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>
              <td>
                <%= "フォロー数：#{user.follower.count}" %>
              </td>
              <td>
                <%= "フォロワー数：#{user.followed.count}" %>
              </td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
<%else%>
  <p>ユーザーはいません</p>
<%end%>

app/views/relationships/follower.html.erb
<h1>Follow Users</h1>
<% if @user.following_user.present? %>
  <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
          <% @user.following_user.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user , :profile_image, size: "40x40", fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>
              <td>
                <%= "フォロー数：#{user.follower.count}" %>
              </td>
              <td>
                <%= "フォロワー数：#{user.followed.count}" %>
              </td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
<%else%>
<p>ユーザーはいません</p>
<%end%>

app/views/searches/search.html.erb
<h2>Search for "<%=@word%>"</h2>
<!--books一覧 -->
<table class="table table-hover table-inverse">
　<% if @range == '2' %>
  <thead>
    <tr>
     <th></th>
     <th>Title</th>
     <th>Opinion</th>
     <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
     <% @book.each do |book| %>
     <tr>
      <td>
       <%= link_to(book.user) do %>
       <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %>
       <% end %>
      </td>
      <td>
       <%= link_to book.title, book, class: "book_#{book.id}" %>
      </td>
      <td><%= book.body %></td>
     </tr>
     <% end %>
  </tbody>

  <% else %>
  <thead>
     <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
     </tr>
   </thead>

   <tbody>
    <% @user.each do |user| %>
     <tr>
      <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
      <td><%= user.name%></td>
      <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
     </tr>
    <% end %>
   </tbody>
   <% end %>
 </table>

app/views/users/_userinfo.html.erb
    <% if book.errors.any? %>
      <%= book.errors.count %>error prohibited this obj from being saved:
      <% book.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
       <%= attachment_image_tag user, :profile_image, format: 'jpeg', size: "100x100", fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= user.name%></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction%></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to "#{user.follower.count}", following_path(user) %></th>
          <tr>
            <th>followers</th>
            <th><%= link_to "#{user.followed.count}", followers_path(user) %></th>
          </tr>
          <tr>
            <th>
            <% unless user == current_user %>
            <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST,class:"btn btn-success"%>
              <% else %>
              <%= link_to 'フォローする', follow_path(user.id), method: :POST,class:"btn btn-success" %>
              <% end %>
            <% end %>
            </th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_45530" do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
      <h2 class="mt-3">
        New book
      </h2>
      <%= form_with model: book, local:true do |f| %>
        <div class="form-group">
          <label>Title</label>
          <%= f.text_field :title, class: "form-control book_title"  %>
        </div>
        <div class="form-group">
          <label>Opinion</label>
          <%= f.text_area:body, class: "form-control book_body" %>
        </div>
        <%= f.submit 'Create Book', class:"btn btn-success" %>
      <% end %>
    </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <%= @user.errors.count %>error prohibited this obj from being saved:
        <% @user.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <label>Name</label>
        <%= f.text_field :name, class:"form-control user_name" %>
      </div>
      <div class="form-group">
        <label>Image</label>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <label>Introduction</label>
        <%= f.text_area :introduction, class:"form-control user_introduction" %>
      </div>
      <div class="form-group"><%= f.submit "Update User", class:"btn btn-secondary" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
    <%= render 'users/userinfo', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user , :profile_image, size: "40x40", fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td>
              <%= "フォロー数：#{user.follower.count}" %>
            </td>
            <td>
              <%= "フォロワー数：#{user.followed.count}" %>
            </td>
            <td>
            <% unless user == current_user %>
              <% if current_user.following?(user) %>
                <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
              <% else %>
                <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
              <% end %>
            <% end %>
            </td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
    <%= render 'users/userinfo', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
          <%= link_to user_path(book.user_id) do %>
            <%= attachment_image_tag book.user, :profile_image, size: '50x50', fallback: "no_image.jpg" %>
          <% end %>
          </td>
          <td>
          <%= link_to book_path(book.id) do %>
            <%= book.title %>
          <% end %>
          </td>
          <td><%= book.body %></td>
          <td>
              <%= link_to "コメント数：#{book.book_comments.count}", book_path(book.id) %>
            </td>
        </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>