config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :index, :edit, :update]
  post 'follow/:id' => 'relationships#create', as: 'follow'
  post 'unfollow/:id' => 'relationships#destroy', as: 'unfollow'
  get 'users/:id/following' => 'relationships#follower', as: 'following'
  get 'users/:id/followers' => 'relationships#followed', as: 'followers'
  get 'search' => 'searches#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def self.search(search, word)
    if search == "forward_match"
                        @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
                        @book = Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
                        @book = Book.where("#{word}")
    elsif search == "partial_match"
                        @book = Book.where("title LIKE?","%#{word}%")
    else
                        @book = Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name,    uniqueness: true, length: { in: 2..20 }
  validates :introduction,    length: { maximum: 50 }
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :favorited_books, through: :favorites, source: :book
  def follow(user_id)
    follower.create(followed_id: user_id)
  end


  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end


  def following?(user)
    following_user.include?(user)
  end

  def self.search(search,word)
    if search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
      @user = User.where("#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  def after_sign_up_path_for(resource)
    user_path(current_user.id)
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book was created successfully"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all.sort {|a,b| b.favorited_users.count <=> a.favorited_users.count}
    @user = current_user
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @user = User.find(@books.user.id)
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id == current_user.id
    else
      redirect_to books_path
    end
  end

  def update
     @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was updated successfully"
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @range = params[:range]
    search = params[:search]
    @word = params[:word]
    if @range == '1'
      @user = User.search(search,@word)
    else
      @book = Book.search(search,@word)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: params[:id])
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "User info was successfully updated"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notification.html.erb
<div class="Notification">
 <% flash.each do |key, value| %>
 <%= content_tag :div, value, class: key %>
 <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/1f23f80937.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path, class:"navbar-brand" do %>
          <span>Bookers</span>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
               <% if user_signed_in? %>
                <li>
                <%= link_to user_path(current_user.id) do %>
                  <span class="fas fa-home nav-link text-light">Home</span>
                <% end %>
                </li>
                <%= link_to users_path do %>
                  <span class="fas fa-users nav-link text-light">Users</span>
                <% end %>
                <%= link_to books_path do %>
                  <span class="fas fa-book-open nav-link text-light">Books</span>
                <% end %>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <span class="fas fa-sign-out-alt nav-link text-light">logout</span>
                <% end %>
              <% else %>
                <%= link_to root_path do %>
                  <span class="fas fa-home nav-link text-light">Home</span>
                <% end %>
                <%= link_to home_about_path do %>
                  <span class="fas fa-link nav-link text-light">About</span>
                <% end %>
                <%= link_to new_user_registration_path do %>
                  <span class="fas fa-user-plus nav-link text-light">Sign up</span>
                <% end %>
                <%= link_to new_user_session_path do %>
                  <span class="fas fa-sign-in-alt nav-link text-light">login</span>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= render 'layouts/notification' %>
<% if user_signed_in? %>
<div class="search">
  <%= form_tag(search_path, method: :get) do %>
　 <%= select_tag 'range' ,options_for_select([['User', '1'], ['Book', '2']]) %>
   <%= select_tag 'search', options_for_select([["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
   <%= text_field_tag (:word) %>
   <%= submit_tag "検索" %>
  <% end %>
</div>
<% end %>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <P>CopyRight Infratop.inc</P>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>